-- Landowners (grunneiere) and their property parcels (teiger), shown as a toggleable
-- map layer alongside the worklog. A parcel is one polygon of one owner's land, optionally
-- linked to a turområde (hub); an owner can hold several parcels across several areas.

CREATE TABLE public.owners (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  gnr integer,
  bnr integer,
  color text NOT NULL DEFAULT '#2f5d3a',
  agreement_status text NOT NULL DEFAULT 'missing' CHECK (agreement_status IN ('ok', 'warn', 'missing')),
  agreement_label text NOT NULL DEFAULT 'Avtale mangler',
  contact_name text,
  phone text,
  email text,
  note text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE TRIGGER set_updated_at_owners BEFORE UPDATE ON public.owners
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.parcels (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  owner_id bigint NOT NULL REFERENCES public.owners(id) ON DELETE CASCADE,
  hub_id bigint REFERENCES public.hubs(id) ON DELETE SET NULL,
  teig integer NOT NULL DEFAULT 1,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX parcels_owner_id_idx ON public.parcels (owner_id);
CREATE INDEX parcels_hub_id_idx ON public.parcels (hub_id);
CREATE INDEX parcels_geom_idx ON public.parcels USING gist (geom);
CREATE TRIGGER set_updated_at_parcels BEFORE UPDATE ON public.parcels
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Read source for the frontend: parcel geometry as GeoJSON plus the area (daa) computed
-- server-side, so the client never has to re-derive polygon area from raw coordinates.
CREATE OR REPLACE VIEW public.parcels_geojson WITH (security_invoker = true) AS
SELECT
  p.id::text AS id,
  p.owner_id::text AS owner_id,
  p.hub_id::text AS hub_id,
  hb.name AS area,
  p.teig,
  ST_Area(p.geom::geography) / 1000 AS daa,
  ST_AsGeoJSON(p.geom)::json AS geometry
FROM public.parcels p
LEFT JOIN public.hubs hb ON p.hub_id = hb.id;

-- RLS: same shape as hubs/gjerdeklyvere/other_points — public read, admin write.
ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON public.owners FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admin insert" ON public.owners FOR INSERT TO authenticated WITH CHECK ((SELECT public.is_admin()));
CREATE POLICY "Admin update" ON public.owners FOR UPDATE TO authenticated USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
CREATE POLICY "Admin delete" ON public.owners FOR DELETE TO authenticated USING ((SELECT public.is_admin()));

ALTER TABLE public.parcels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON public.parcels FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admin insert" ON public.parcels FOR INSERT TO authenticated WITH CHECK ((SELECT public.is_admin()));
CREATE POLICY "Admin update" ON public.parcels FOR UPDATE TO authenticated USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
CREATE POLICY "Admin delete" ON public.parcels FOR DELETE TO authenticated USING ((SELECT public.is_admin()));
