-- Turkart: the 7-kind point taxonomy (with subtypes) and routes as first-class entities.
--
-- Point kinds: gjerdeklyver (own table), skilt, tilrettelegging, turinfo, benk, parkering, annet
-- (other_points.kind). Subtypes, labels and "Om …" copy live in src/models/worklog.js — only the
-- allowed subtype keys are enforced here. Remapping existing rows onto the new kinds is a separate
-- data migration (…_backfill_point_taxonomy.sql).
--
-- Colour note (kept in the frontend, recorded here so it isn't "fixed" by accident): benk reuses the
-- old drenering blue #2c6e8a, and the rød route difficulty reuses the old merking red #c8242b. Both old
-- kinds stop being top-level kinds, so the collisions never appear side by side.

-- Every view below is rebuilt, and all_features_geojson depends on other_points.geom whose type changes
DROP VIEW IF EXISTS public.all_features_geojson;

-- ── Gjerdeklyvere: subtype + dog note. Geometry stays Point-only. ─────────────────────────────────
ALTER TABLE public.gjerdeklyvere
  ADD COLUMN subtype text CHECK (subtype IS NULL OR subtype IN ('standard', 'hundeluke', 'turstiport', 'turstitrapp', 'ombygd')),
  ADD COLUMN hund text;

-- ── Other points: subtype, parking capacity, and the pre-taxonomy kind for reversibility ─────────
ALTER TABLE public.other_points
  ADD COLUMN subtype text,
  ADD COLUMN plasser text,
  ADD COLUMN legacy_kind text;

-- NULL is always allowed ("ukjent"). tilrettelegging is the union of the designed structures
-- (bru … steinsetting) and the groundwork carried over from the old worklog types (drenering, grus,
-- nysti). gjerdeklyver is listed because a few legacy rows are gjerdeklyvere living in other_points.
ALTER TABLE public.other_points ADD CONSTRAINT other_points_subtype_chk CHECK (
  subtype IS NULL
  OR (kind = 'skilt' AND subtype IN ('turvett', 'info'))
  OR (kind = 'tilrettelegging' AND subtype IN ('bru', 'klopp', 'trapp', 'rekkverk', 'steinsetting', 'drenering', 'grus', 'nysti'))
  OR (kind = 'gjerdeklyver' AND subtype IN ('standard', 'hundeluke', 'turstiport', 'turstitrapp', 'ombygd'))
);

-- Per-kind geometry: tilrettelegging and annet can be a point, a line (klopp, grus …) or an area
-- (steinsetting …); every other kind is a point. A klopp belongs to the path, not to a route: drawn
-- once as a line here, route_features attaches it to every route that passes it — so there is no
-- separate path_sections table. Later trail-quality kinds (natursti, improved surface) are just new
-- subtypes with line geometry.
ALTER TABLE public.other_points ALTER COLUMN geom TYPE geometry(Geometry, 4326);
ALTER TABLE public.other_points ADD CONSTRAINT other_points_geom_kind_chk CHECK (
  geometrytype(geom) = 'POINT'
  OR (kind IN ('tilrettelegging', 'annet') AND geometrytype(geom) IN ('LINESTRING', 'POLYGON'))
);

-- ── Owners: animals grazing on the property ───────────────────────────────────────────────────────
ALTER TABLE public.owners ADD COLUMN dyr text;

-- ── Routes ────────────────────────────────────────────────────────────────────────────────────────
-- Length, time and which points lie along a route are all derived (routes_geojson / route_features),
-- never stored. climb and direction are free text as designed ('140 m', 'med klokka fra parkeringen').
CREATE TABLE public.routes (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hub_id bigint REFERENCES public.hubs(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  images text[] DEFAULT '{}'::text[],
  difficulty text NOT NULL DEFAULT 'gronn' CHECK (difficulty IN ('gronn', 'bla', 'rod', 'svart')),
  shape text NOT NULL DEFAULT 'rundtur' CHECK (shape IN ('rundtur', 'turretur', 'ab')),
  climb text,
  direction text,
  geom geometry(LineString, 4326) NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX routes_hub_id_idx ON public.routes (hub_id);
CREATE INDEX routes_geom_idx ON public.routes USING gist (geom);
CREATE TRIGGER set_updated_at_routes BEFORE UPDATE ON public.routes
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.routes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON public.routes FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admin insert" ON public.routes FOR INSERT TO authenticated WITH CHECK ((SELECT public.is_admin()));
CREATE POLICY "Admin update" ON public.routes FOR UPDATE TO authenticated USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
CREATE POLICY "Admin delete" ON public.routes FOR DELETE TO authenticated USING ((SELECT public.is_admin()));

-- ── Views ─────────────────────────────────────────────────────────────────────────────────────────
-- Single point used for markers, lists and distance sorting, whatever the feature's geometry
CREATE OR REPLACE FUNCTION public.feature_anchor(g geometry)
RETURNS geometry
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE geometrytype(g)
    WHEN 'POINT' THEN g
    WHEN 'LINESTRING' THEN ST_LineInterpolatePoint(g, 0.5)
    ELSE ST_PointOnSurface(g)
  END
$$;

-- Same columns as before plus, appended: taxonomy fields, the table a row lives in (a legacy
-- gjerdeklyver can sit in other_points), and geometry-derived anchor/length/area so the client never
-- computes extent itself. length_m/area_m2 are 0 (not NULL) when they don't apply.
CREATE VIEW public.all_features_geojson WITH (security_invoker = true) AS
SELECT
  h.id::text AS id,
  h.name AS slug,
  h.title,
  'hub' AS kind,
  NULL::text AS feature_group,
  NULL::text AS icon,
  h.popup,
  h.description,
  h.includes,
  h.difficulty,
  COALESCE(TO_CHAR(h.last_updated,'YYYY-MM-DD'), NULL) AS last_updated,
  h.images,
  h.created_at,
  h.updated_at,
  h.color,
  ST_AsGeoJSON(h.geom)::json AS geometry,
  ST_AsGeoJSON(COALESCE(h.location, ST_PointOnSurface(h.geom)))::json AS location,
  NULL::text AS subtype,
  NULL::text AS hund,
  NULL::text AS plasser,
  NULL::text AS legacy_kind,
  'hubs'::text AS source_table,
  geometrytype(h.geom) AS geom_type,
  ST_AsGeoJSON(COALESCE(h.location, ST_PointOnSurface(h.geom)))::json AS anchor,
  0::double precision AS length_m,
  COALESCE(ST_Area(h.geom::geography), 0) AS area_m2
FROM public.hubs h
UNION ALL
SELECT
  g.id::text AS id,
  NULL::text AS slug,
  g.title,
  'gjerdeklyver' AS kind,
  hb.name AS feature_group,
  g.icon,
  g.popup,
  g.description,
  g.includes,
  g.difficulty,
  COALESCE(TO_CHAR(g.last_updated,'YYYY-MM-DD'), NULL) AS last_updated,
  g.images,
  g.created_at,
  g.updated_at,
  g.color,
  ST_AsGeoJSON(g.geom)::json AS geometry,
  NULL::json AS location,
  g.subtype,
  g.hund,
  NULL::text AS plasser,
  NULL::text AS legacy_kind,
  'gjerdeklyvere'::text AS source_table,
  geometrytype(g.geom) AS geom_type,
  ST_AsGeoJSON(g.geom)::json AS anchor,
  0::double precision AS length_m,
  0::double precision AS area_m2
FROM public.gjerdeklyvere g
LEFT JOIN public.hubs hb ON g.hub_id = hb.id
UNION ALL
SELECT
  p.id::text AS id,
  NULL::text AS slug,
  p.title,
  p.kind AS kind,
  hb.name AS feature_group,
  p.icon,
  p.popup,
  p.description,
  p.includes,
  p.difficulty,
  COALESCE(TO_CHAR(p.last_updated,'YYYY-MM-DD'), NULL) AS last_updated,
  p.images,
  p.created_at,
  p.updated_at,
  p.color,
  ST_AsGeoJSON(p.geom)::json AS geometry,
  NULL::json AS location,
  p.subtype,
  NULL::text AS hund,
  p.plasser,
  p.legacy_kind,
  'other_points'::text AS source_table,
  geometrytype(p.geom) AS geom_type,
  ST_AsGeoJSON(public.feature_anchor(p.geom))::json AS anchor,
  ST_Length(p.geom::geography) AS length_m,
  ST_Area(p.geom::geography) AS area_m2
FROM public.other_points p
LEFT JOIN public.hubs hb ON p.hub_id = hb.id;

CREATE VIEW public.routes_geojson WITH (security_invoker = true) AS
SELECT
  r.id::text AS id,
  r.hub_id::text AS hub_id,
  r.title,
  r.description,
  r.images,
  r.difficulty,
  r.shape,
  r.climb,
  r.direction,
  r.updated_at,
  ST_Length(r.geom::geography) / 1000 AS km,
  ST_AsGeoJSON(r.geom)::json AS geometry
FROM public.routes r;

-- Everything within 15 m of a route, with its position along it in km. Which gjerdeklyvere and
-- klopper lie on a route — and where — is worked out here, so nothing is registered twice. Linear
-- features also get km_fra/km_til (their start and end along the route, ordered so km_fra <= km_til).
CREATE VIEW public.route_features WITH (security_invoker = true) AS
WITH features AS (
  SELECT 'gjerdeklyvere'::text AS feature_table, g.id, 'gjerdeklyver'::text AS kind, g.subtype, g.title, g.geom
  FROM public.gjerdeklyvere g
  UNION ALL
  SELECT 'other_points'::text, p.id, p.kind, p.subtype, p.title, p.geom
  FROM public.other_points p
),
located AS (
  SELECT
    r.id AS route_id,
    f.feature_table,
    f.id AS feature_id,
    f.kind,
    f.subtype,
    f.title,
    geometrytype(f.geom) AS geom_type,
    ST_Length(r.geom::geography) / 1000 AS route_km,
    ST_LineLocatePoint(r.geom, public.feature_anchor(f.geom)) AS pos,
    CASE WHEN geometrytype(f.geom) = 'LINESTRING' THEN ST_LineLocatePoint(r.geom, ST_StartPoint(f.geom)) END AS pos_start,
    CASE WHEN geometrytype(f.geom) = 'LINESTRING' THEN ST_LineLocatePoint(r.geom, ST_EndPoint(f.geom)) END AS pos_end,
    ST_Length(f.geom::geography) AS length_m
  FROM public.routes r
  JOIN features f ON ST_DWithin(r.geom::geography, f.geom::geography, 15)
)
SELECT
  route_id::text AS route_id,
  feature_table,
  feature_id::text AS feature_id,
  kind,
  subtype,
  title,
  geom_type,
  pos * route_km AS km,
  LEAST(pos_start, pos_end) * route_km AS km_fra,
  GREATEST(pos_start, pos_end) * route_km AS km_til,
  length_m
FROM located;

-- Owners whose parcels a route crosses ("Grunneiere langs ruta" / "Ruter over eiendommen")
CREATE VIEW public.route_owners WITH (security_invoker = true) AS
SELECT DISTINCT
  r.id::text AS route_id,
  p.owner_id::text AS owner_id
FROM public.routes r
JOIN public.parcels p ON ST_Intersects(r.geom, p.geom);
