-- STEP-BY-STEP MIGRATION: Simpler, debuggable version
-- Run this entire script in your Supabase SQL editor or DBeaver
-- It will create new tables and migrate your 15 rows from map_features

-- ========== STEP 1: Enable PostGIS ==========
CREATE EXTENSION IF NOT EXISTS postgis;

-- ========== STEP 2: Create helper function ==========
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ========== STEP 3: Create hubs table ==========
CREATE TABLE public.hubs (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  popup text,
  includes text,
  difficulty text,
  last_updated date,
  images text[] DEFAULT '{}'::text[],
  color text,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX hubs_geom_idx ON public.hubs USING gist (geom);
CREATE TRIGGER set_updated_at_hubs BEFORE UPDATE ON public.hubs
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ========== STEP 4: Create gjerdeklyvere table ==========
CREATE TABLE public.gjerdeklyvere (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hub_id bigint NOT NULL REFERENCES public.hubs(id) ON DELETE CASCADE,
  title text NOT NULL,
  icon text,
  popup text,
  description text,
  includes text,
  difficulty text,
  last_updated date,
  images text[] DEFAULT '{}'::text[],
  color text,
  geom geometry(Point, 4326) NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX gjerdeklyvere_hub_id_idx ON public.gjerdeklyvere (hub_id);
CREATE INDEX gjerdeklyvere_geom_idx ON public.gjerdeklyvere USING gist (geom);
CREATE TRIGGER set_updated_at_gjerdeklyvere BEFORE UPDATE ON public.gjerdeklyvere
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ========== STEP 5: Create other_points table ==========
CREATE TABLE public.other_points (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hub_id bigint REFERENCES public.hubs(id) ON DELETE SET NULL,
  title text NOT NULL,
  kind text DEFAULT 'poi',
  icon text,
  popup text,
  description text,
  includes text,
  difficulty text,
  last_updated date,
  images text[] DEFAULT '{}'::text[],
  color text,
  geom geometry(Point, 4326) NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX other_points_hub_id_idx ON public.other_points (hub_id);
CREATE INDEX other_points_kind_idx ON public.other_points (kind);
CREATE INDEX other_points_geom_idx ON public.other_points USING gist (geom);
CREATE TRIGGER set_updated_at_other_points BEFORE UPDATE ON public.other_points
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ========== STEP 6: Insert hubs ==========
INSERT INTO public.hubs (name, title, description, popup, includes, difficulty, last_updated, images, color, geom, created_at, updated_at)
SELECT
  COALESCE(slug, title) AS name,
  title,
  description,
  popup,
  includes,
  difficulty,
  CASE WHEN last_updated ~ '^\d{4}-\d{2}-\d{2}' THEN (last_updated)::date ELSE NULL END,
  images,
  color,
  CASE
    WHEN GeometryType(geom) IN ('POLYGON','MULTIPOLYGON') THEN ST_Multi(geom)
    WHEN GeometryType(geom) = 'GEOMETRYCOLLECTION' THEN ST_Multi(ST_CollectionExtract(geom,3))
    ELSE ST_Multi(ST_Buffer(ST_Envelope(geom),0.0001))
  END::geometry(MultiPolygon,4326),
  created_at,
  updated_at
FROM public.map_features
WHERE LOWER(kind) = 'hub';

-- ========== STEP 7: Insert gjerdeklyvere (icon='gjerdeklyver' OR includes like gjerdeklyver) ==========
INSERT INTO public.gjerdeklyvere (hub_id, title, icon, popup, description, includes, difficulty, last_updated, images, color, geom, created_at, updated_at)
SELECT
  h.id,
  mf.title,
  mf.icon,
  mf.popup,
  mf.description,
  mf.includes,
  mf.difficulty,
  CASE WHEN mf.last_updated ~ '^\d{4}-\d{2}-\d{2}' THEN (mf.last_updated)::date ELSE NULL END,
  mf.images,
  mf.color,
  CASE
    WHEN GeometryType(mf.geom) IN ('POINT','MULTIPOINT') THEN ST_Force2D(mf.geom)
    ELSE ST_Force2D(ST_Centroid(mf.geom))
  END::geometry(Point,4326),
  mf.created_at,
  mf.updated_at
FROM public.map_features mf
LEFT JOIN public.hubs h ON h.name = mf.feature_group
WHERE LOWER(COALESCE(mf.icon,'')) = 'gjerdeklyver'
   OR (mf.includes IS NOT NULL AND LOWER(mf.includes) LIKE '%gjerdeklyver%');

-- ========== STEP 8: Insert other_points (trails, POIs, etc.) ==========
INSERT INTO public.other_points (hub_id, title, kind, icon, popup, description, includes, difficulty, last_updated, images, color, geom, created_at, updated_at)
SELECT
  h.id,
  mf.title,
  LOWER(COALESCE(mf.kind,'poi')),
  mf.icon,
  mf.popup,
  mf.description,
  mf.includes,
  mf.difficulty,
  CASE WHEN mf.last_updated ~ '^\d{4}-\d{2}-\d{2}' THEN (mf.last_updated)::date ELSE NULL END,
  mf.images,
  mf.color,
  CASE
    WHEN GeometryType(mf.geom) IN ('POINT','MULTIPOINT') THEN ST_Force2D(mf.geom)
    ELSE ST_Force2D(ST_Centroid(mf.geom))
  END::geometry(Point,4326),
  mf.created_at,
  mf.updated_at
FROM public.map_features mf
LEFT JOIN public.hubs h ON h.name = mf.feature_group
WHERE LOWER(mf.kind) <> 'hub'
  AND NOT (LOWER(COALESCE(mf.icon,'')) = 'gjerdeklyver' OR (mf.includes IS NOT NULL AND LOWER(mf.includes) LIKE '%gjerdeklyver%'));

-- ========== STEP 9: Create compatibility view ==========
CREATE OR REPLACE VIEW public.all_features_geojson AS
SELECT
  h.id::text AS id,
  h.name AS slug,
  h.title,
  'hub' AS kind,
  NULL::text AS feature_group,
  NULL::text AS icon,
  h.popup,
  h.description,
  h.includes,
  h.difficulty,
  COALESCE(TO_CHAR(h.last_updated,'YYYY-MM-DD'), NULL) AS last_updated,
  h.images,
  h.created_at,
  h.updated_at,
  h.color,
  ST_AsGeoJSON(h.geom)::json AS geometry
FROM public.hubs h
UNION ALL
SELECT
  g.id::text AS id,
  NULL::text AS slug,
  g.title,
  'gjerdeklyver' AS kind,
  hb.name AS feature_group,
  g.icon,
  g.popup,
  g.description,
  g.includes,
  g.difficulty,
  COALESCE(TO_CHAR(g.last_updated,'YYYY-MM-DD'), NULL) AS last_updated,
  g.images,
  g.created_at,
  g.updated_at,
  g.color,
  ST_AsGeoJSON(g.geom)::json AS geometry
FROM public.gjerdeklyvere g
LEFT JOIN public.hubs hb ON g.hub_id = hb.id
UNION ALL
SELECT
  p.id::text AS id,
  NULL::text AS slug,
  p.title,
  p.kind AS kind,
  hb.name AS feature_group,
  p.icon,
  p.popup,
  p.description,
  p.includes,
  p.difficulty,
  COALESCE(TO_CHAR(p.last_updated,'YYYY-MM-DD'), NULL) AS last_updated,
  p.images,
  p.created_at,
  p.updated_at,
  p.color,
  ST_AsGeoJSON(p.geom)::json AS geometry
FROM public.other_points p
LEFT JOIN public.hubs hb ON p.hub_id = hb.id;

-- ========== VERIFICATION ==========
-- After running, check these counts:
-- SELECT COUNT(*) FROM public.hubs;
-- SELECT COUNT(*) FROM public.gjerdeklyvere;
-- SELECT COUNT(*) FROM public.other_points;
-- SELECT COUNT(*) FROM public.all_features_geojson;
